"""Add security_id, market_code, and new action types

Revision ID: 1e23297fda48
Revises: 8918dbb30d6a
Create Date: 2025-10-25 23:03:28.836285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e23297fda48'
down_revision: Union[str, Sequence[str], None] = '8918dbb30d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_actions', sa.Column('security_id', sa.Integer(), nullable=True))
    op.add_column('corporate_actions', sa.Column('market_code', sa.String(length=10), nullable=True))
    op.add_column('corporate_actions', sa.Column('symbol', sa.String(length=50), nullable=True))
    op.add_column('corporate_actions', sa.Column('isin', sa.String(length=50), nullable=True))
    op.add_column('corporate_actions', sa.Column('old_face_value', sa.Float(), nullable=True))
    op.add_column('corporate_actions', sa.Column('new_face_value', sa.Float(), nullable=True))
    op.add_column('corporate_actions', sa.Column('split_ratio', sa.String(length=50), nullable=True))
    op.add_column('corporate_actions', sa.Column('rights_ratio_numerator', sa.Integer(), nullable=True))
    op.add_column('corporate_actions', sa.Column('rights_ratio_denominator', sa.Integer(), nullable=True))
    op.add_column('corporate_actions', sa.Column('rights_price', sa.Float(), nullable=True))
    op.drop_constraint(op.f('uix_company_action_dates'), 'corporate_actions', type_='unique')
    op.create_index(op.f('ix_corporate_actions_market_code'), 'corporate_actions', ['market_code'], unique=False)
    op.create_index(op.f('ix_corporate_actions_security_id'), 'corporate_actions', ['security_id'], unique=False)
    op.create_unique_constraint('uix_company_action_market_dates', 'corporate_actions', ['company_name', 'action_type', 'market_code', 'announcement_date', 'ex_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_company_action_market_dates', 'corporate_actions', type_='unique')
    op.drop_index(op.f('ix_corporate_actions_security_id'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_market_code'), table_name='corporate_actions')
    op.create_unique_constraint(op.f('uix_company_action_dates'), 'corporate_actions', ['company_name', 'action_type', 'announcement_date', 'ex_date'])
    op.drop_column('corporate_actions', 'rights_price')
    op.drop_column('corporate_actions', 'rights_ratio_denominator')
    op.drop_column('corporate_actions', 'rights_ratio_numerator')
    op.drop_column('corporate_actions', 'split_ratio')
    op.drop_column('corporate_actions', 'new_face_value')
    op.drop_column('corporate_actions', 'old_face_value')
    op.drop_column('corporate_actions', 'isin')
    op.drop_column('corporate_actions', 'symbol')
    op.drop_column('corporate_actions', 'market_code')
    op.drop_column('corporate_actions', 'security_id')
    # ### end Alembic commands ###
