"""Initial migration - corporate_actions table

Revision ID: 8918dbb30d6a
Revises: 
Create Date: 2025-10-25 20:15:09.080437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8918dbb30d6a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=500), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('announcement_date', sa.String(length=50), nullable=True),
    sa.Column('ex_date', sa.String(length=50), nullable=True),
    sa.Column('record_date', sa.String(length=50), nullable=True),
    sa.Column('final_date', sa.String(length=50), nullable=True),
    sa.Column('dividend_rate', sa.Float(), nullable=True),
    sa.Column('dividend_type', sa.String(length=100), nullable=True),
    sa.Column('ratio_numerator', sa.Float(), nullable=True),
    sa.Column('ratio_denominator', sa.Float(), nullable=True),
    sa.Column('security_type', sa.String(length=200), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name', 'action_type', 'announcement_date', 'ex_date', name='uix_company_action_dates')
    )
    op.create_index(op.f('ix_corporate_actions_action_type'), 'corporate_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_corporate_actions_company_name'), 'corporate_actions', ['company_name'], unique=False)
    op.create_index(op.f('ix_corporate_actions_ex_date'), 'corporate_actions', ['ex_date'], unique=False)
    op.create_index(op.f('ix_corporate_actions_id'), 'corporate_actions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corporate_actions_id'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_ex_date'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_company_name'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_action_type'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    # ### end Alembic commands ###
